"""Make user_id nullable for guest carts

Revision ID: 104a83994dd7
Revises: ff8ae3971280
Create Date: 2026-03-26 04:08:32.546610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104a83994dd7'
down_revision = 'ff8ae3971280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
