"""Add user_id to support_conversations

Revision ID: c20ddc707c43
Revises: 104a83994dd7
Create Date: 2026-03-26 04:57:39.688123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20ddc707c43'
down_revision = '104a83994dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_support_conversations_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('support_ratings', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ratings', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('support_conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_support_conversations_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###